---
all:
  children:
    web:
      hosts:
        web-01.staging.internal:
          deploy_canary: true
        web-02.staging.internal:
    db:
      hosts:
        db-01.staging.internal:
          postgres_role: primary
    lb:
      hosts:
        lb-01.staging.internal:
    app:
      children:
        web:
        db:
